name: rockband_weather_app
description: A RockBand Staff app to track the current
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6
  google_fonts: ^0.3.2
  flutter_secure_storage: ^3.3.1+1
  sqflite: ^1.1.7+1
  get_it: ^3.1.0
  weather_icons: ^2.0.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: any
  flutter_launcher_icons: any
  build_runner: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/ic_app.png"
  adaptive_icon_background: "#1C2834"
  adaptive_icon_foreground: "images/img_guitar.png"

flutter:
  uses-material-design: true

  assets:
    - images/img_guitar.png
    - images/img_rain.png
    - images/ic_app.png
